[satellite]
name = "MSG Indian Ocean"

[navigation]
satellite_radius_km = 42164.0
full_disk_scan_min = 15.0

[orientation]
flip_vertical = true
flip_horizontal = true

[grids."3000"]
angular_sampling_rad = 8.384333e-5

[channels]
VIS006 = 640
